[
  %{
    "EMP:NMBR" => 2.0,
    "LAST" => "Stegman",
    "FIRST" => "Joe",
    "ADDR" => "4421 W 166th ST",
    "CITY" => "LAWNDALE",
    "ZIP:CODE" => "90260-",
    "PHONE" => "370-4846",
    "SSN" => "257-89-9632",
    "HIREDATE" => "07/31/82",
    "TERMDATE" => "/  /",
    "CLASS" => "TEC",
    "DEPT" => "TCH",
    "PAYRATE" => 6.0,
    "START:PAY" => 6.0
  },
  %{
    "EMP:NMBR" => 3.0,
    "LAST" => "Hemeryick",
    "FIRST" => "Beth",
    "ADDR" => "",
    "CITY" => "",
    "ZIP:CODE" => "-",
    "PHONE" => "-",
    "SSN" => "-  -",
    "HIREDATE" => "10/12/82",
    "TERMDATE" => "",
    "CLASS" => "SEC",
    "DEPT" => "PM",
    "PAYRATE" => 5.0,
    "START:PAY" => 5.0
  },
  %{
    "EMP:NMBR" => 4.0,
    "LAST" => "Taylor",
    "FIRST" => "Jim",
    "ADDR" => "10150 W. Jefferson B",
    "CITY" => "Culver City",
    "ZIP:CODE" => "90230-",
    "PHONE" => "204-5570",
    "SSN" => "254-12-3689",
    "HIREDATE" => "08/23/80",
    "TERMDATE" => "06/13/83",
    "CLASS" => "RTM",
    "DEPT" => "SLS",
    "PAYRATE" => 18.0,
    "START:PAY" => 18.0
  },
  %{
    "EMP:NMBR" => 6.0,
    "LAST" => "Johnson",
    "FIRST" => "Joe",
    "ADDR" => "767 erererer",
    "CITY" => "tyhgghh",
    "ZIP:CODE" => "99393-9",
    "PHONE" => "332-3232",
    "SSN" => "258-74-1258",
    "HIREDATE" => "12/12/12",
    "TERMDATE" => "/  /",
    "CLASS" => "LLL",
    "DEPT" => "LLL",
    "PAYRATE" => 8989.0,
    "START:PAY" => 8989.0
  },
  %{
    "EMP:NMBR" => 7.0,
    "LAST" => "Thomas",
    "FIRST" => "Dale",
    "ADDR" => "3737ekdmvljvlrf",
    "CITY" => "lhefkjefwf",
    "ZIP:CODE" => "30393-8393",
    "PHONE" => "983-9383",
    "SSN" => "838-38-3828",
    "HIREDATE" => "38/28/28",
    "TERMDATE" => "",
    "CLASS" => "383",
    "DEPT" => "838",
    "PAYRATE" => 3838.383,
    "START:PAY" => 3838.383
  },
  %{
    "EMP:NMBR" => 8.0,
    "LAST" => "AAAAAAA",
    "FIRST" => "AAAAAAAAA",
    "ADDR" => "AAAAAAAAA",
    "CITY" => "AAAAAA",
    "ZIP:CODE" => "22222-2222",
    "PHONE" => "222-2222",
    "SSN" => "222-22-2222",
    "HIREDATE" => "22/22/22",
    "TERMDATE" => "",
    "CLASS" => "AAA",
    "DEPT" => "AAA",
    "PAYRATE" => 23.0,
    "START:PAY" => 23.0
  },
  %{
    "EMP:NMBR" => 9.0,
    "LAST" => "TERRIFIC",
    "FIRST" => "TOM",
    "ADDR" => "123 MOCKINGBIRD CT.",
    "CITY" => "WINIMUCKU",
    "ZIP:CODE" => "11111-1111",
    "PHONE" => "111-1111",
    "SSN" => "121-21-2121",
    "HIREDATE" => "06/13/83",
    "TERMDATE" => "",
    "CLASS" => "",
    "DEPT" => "",
    "PAYRATE" => 5555.55,
    "START:PAY" => 5555.55
  },
  %{
    "EMP:NMBR" => 10.0,
    "LAST" => "",
    "FIRST" => "",
    "ADDR" => "",
    "CITY" => "",
    "ZIP:CODE" => "-",
    "PHONE" => "-",
    "SSN" => "-  -",
    "HIREDATE" => "/  /",
    "TERMDATE" => "",
    "CLASS" => "",
    "DEPT" => "",
    "PAYRATE" => 0.0,
    "START:PAY" => nil
  },
  %{
    "EMP:NMBR" => 11.0,
    "LAST" => "",
    "FIRST" => "",
    "ADDR" => "",
    "CITY" => "",
    "ZIP:CODE" => "-",
    "PHONE" => "-",
    "SSN" => "-  -",
    "HIREDATE" => "/  /",
    "TERMDATE" => "",
    "CLASS" => "",
    "DEPT" => "",
    "PAYRATE" => 0.0,
    "START:PAY" => nil
  }
]
